### ISSUE TITLE
Make scrutinizer pass

### ISSUE THREAD

**Issue by j4m3s** [phpgt/csrf#17]
I can't tell what's going wrong. If you check the history of my circleci pull request you'll see it did pass once... but goodness knows why. 

It appears to be failing to consolidate the results of the various steps.

**Comment by j4m3s** [comment]
@g105b I've lost the plot.  Is it passing on scrutinizer now?  I can't tell what's going on any more!

**Comment by j4m3s** [comment]
Suggest closing this - the scrutinizer checks are passing as-of PR #19, though I have no idea what's changed.

**Comment by g105b** [comment]
Looking at it now, it's a really odd one. We may have found a bug with scrutinizer here, but seeing as it's passing now there's no need to stress about it.
