### ISSUE TITLE
Limit the memory footprint on busy sites

### ISSUE THREAD

**Issue by j4m3s** [phpgt/csrf#18]
Spawned from #16. 

On busy sites with many forms per page, long session timeouts and many users the amount of memory used for storing all these tokens could become significant. 

Obvious options to resolve include a timeout or a limit to the number of tokens in circulation per user. 

The timeout is not optimal because it would have to be long (2 hours?) to allow users to take a call or be part way through filling out a form then doing something else etc

The fixed number of tokens seems more useful as it can be tuned to an appropriate depth for a given application - a number much smaller than the total number of tokens generated over a period of hours.  HOWEVER, should a user leave one tab open then start working on another they could invalidate the tokens associated with the first page.  This could be mitigated by setting the limit to a fairly high number (1,000?) but the risk would remain. 

Thoughts @g105b?

**Comment by g105b** [comment]
Assuming multi-byte strings are used in tokens (they're not), and the token is 4096 characters long, having a million users with a thousand forms open would use 16 GB.

If you're serving a million users in the same session timeframe, this amount of RAM isn't a problem. It'll be load balanced across multiple nodes anyway.

That being said, [memory_get_usage](http://php.net/manual/en/function.memory-get-usage.php) can be used to see how much memory is used and is available - we could allocate a proportion of the available memory for CSRF tokens?

If that seems overkill, 1,000 seems a good default.
