### ISSUE TITLE
HTMLDocument::forms iteration

### ISSUE THREAD

**Issue by g105b** [phpgt/csrf#2]
There's already a `form` property on HTMLDocuments - iterate over this?

**Comment by j4m3s** [comment]
The HTMLDocument->form seems to always be null.  I've added a test to my fork of phpgt/dom - will submit a PR so you can take a look and merge it into a new dom branch to resolve if it's actually a defect (rather than me trying to use it incorrectly).

**Comment by j4m3s** [comment]
See PR phpgt/dom#21 and issue phpgt/dom#22
