### ISSUE TITLE
Use case: sending token as HTTP header?

### ISSUE THREAD

**Issue by g105b** [PhpGt/Csrf#27]
When updating parts of the page using JavaScript, rather than having to parse the response for form tags and extract the input elements, it would be really useful to have the tokens provided by HTTP tokens.
1. Are there any security implications of doing this?
2. How would responses containing multiple forms be handled?

**Comment by g105b** [comment]
2. HTTP headers can already pass multiple data. See HTTP `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`.

**Comment by j4m3s** [comment]
Do you mean the server providing a token using a custom header, or the client submitting the token in a custom header?  OWASP discuss (and endorse, albeit they list it as lowest in order of strength of defense) on their [CSRF page](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#CSRF_Specific_Defense).  a X-CSRF-TOKEN header would seem to be an obvious choice.

If you meant a way for javascript to get the token in the first place without parsing one or more forms: Either a custom cookie set by the server, or (rather more simply - and as adopted by laravel): the library could set a ```<meta name="csrf-token" content="xyz123"/>``` tag in the page head.

**Comment by g105b** [comment]
Was mainly asking if there was any implications in using a header for this rather than putting it in the body - some use cases I can think of would be really useful using headers, such as when doing ajax requests.

**Comment by j4m3s** [comment]
Sorry, I wasn't clear.  When you say "using headers for this", do you mean for receiving a token from the server or submitting a token with a request?

**Comment by g105b** [comment]
Yeah there are cases where a developer may want to submit form data without using an actual form in the HTML... to retrieve and send the correct tokens we could parse the page for the form's csrf, use the meta tag as in #33, or read response headers.

**Comment by g105b** [comment]
Carry on the implementation from #44 - response header should be comma separated.

**Comment by g105b** [comment]
Tracked in phpgt/webengine#572
