### ISSUE TITLE
Add csrf token meta tag to <head>

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Csrf#33]
Currently, javscript would have to parse the token out of a form somewhere in the page (assuming one exists).  Adding a specific tag to the head (which is reliably in the same place) would simplify the javascript logic considerably.

**Comment by g105b** [comment]
Good feature to add, just keep in mind a concern I raised on #27 - how to handle a page with more than one form.

**Comment by j4m3s** [comment]
There are three obvious options if you want to submit the same form repeatedly using Javascript:
  1. We add a new "Token per session" option which doesn't burn the token when it's used.
  2. Parse the new meta tag out of the page response when you submit the form (assumes a page is always returned...)
  3. Or implement a REST-like API that allows the client to get a fresh token.

**Comment by g105b** [comment]
4. The page being requested via JavaScript responds with an `X-CSRF-TOKEN` header, which JavaScript will use to update the form on the page with.
