### ISSUE TITLE
Automate tests in CircleCI

### ISSUE THREAD

**Issue by g105b** [phpgt/csrf#4]

**Comment by g105b** [comment]
I can't work out why it is failing to manage dependencies.

https://circleci.com/gh/phpgt/csrf/5

@j4m3s any idea?

**Comment by j4m3s** [comment]
Looks like  xdebug isn't enabled on the CircleCI server (it is enabled by default on Travis but not CircleCI).  It's not something that composer can install - it just checks to make sure it's there and barfs if not.  

I'll update the circle.yml file which should fix it.

**Comment by g105b** [comment]
the dom repo passes in CircleCI, here's the circle.yml: https://github.com/phpgt/dom/blob/master/circle.yml

**Comment by j4m3s** [comment]
But you don't have the dev-dependency for xdebug in composer.json, so it doesn't warn you that xdebug isn't enabled.  So circle isn't doing the code coverage.
